# Generated by Django 5.2.6 on 2025-09-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='corem',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sigla_estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
