# Generated by Django 5.2.6 on 2025-10-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_corem_user_sigla_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='corem',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sigla_estado',
        ),
        migrations.AddField(
            model_name='user',
            name='coren',
            field=models.CharField(blank=True, help_text='COREN registration number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, help_text='Institution/Hospital', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', help_text='Full name of the user', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, help_text='Medical specialty', max_length=100, null=True),
        ),
    ]
