# Generated by Django 5.2.6 on 2025-10-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_corem_user_sigla_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='corem',
            new_name='corem_number',
        ),
    ]
