# Generated by Django 5.2.6 on 2025-10-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_corem_remove_user_sigla_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
        migrations.AlterField(
            model_name='user',
            name='coren',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='Not informed', max_length=255, null=True),
        ),
    ]
