services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skin_one
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/skin_one