# Generated by Django 5.2.6 on 2025-09-27 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('stage1', 'Stage 1'), ('stage2', 'Stage 2'), ('stage3', 'Stage 3'), ('stage4', 'Stage 4'), ('normal', 'Normal'), ('notapplicable', 'Not Applicable'), ('notunderstand', 'Not Understand')], help_text='Classification result for the image', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Additional comments about the classification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='images.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
