# Generated by Django 5.2.6 on 2025-10-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='comment',
        ),
        migrations.AddField(
            model_name='classification',
            name='observations',
            field=models.TextField(blank=True, help_text='Additional observations about the classification', null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='stage',
            field=models.CharField(choices=[('estagio1', 'Estágio 1'), ('estagio2', 'Estágio 2'), ('estagio3', 'Estágio 3'), ('estagio4', 'Estágio 4'), ('nao_classificavel', 'Não Classificável'), ('dtpi', 'DTPI')], default='nao_classificavel', help_text='Classification stage for the image', max_length=20),
        ),
    ]
