# Generated by Django 5.2.6 on 2025-10-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_remove_classification_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='stage',
            field=models.CharField(choices=[('stage1', 'Estágio 1'), ('stage2', 'Estágio 2'), ('stage3', 'Estágio 3'), ('stage4', 'Estágio 4'), ('not_classifiable', 'Not Classifiable'), ('dtpi', 'DTPI')], default='nao_classificavel', help_text='Classification stage for the image', max_length=20),
        ),
    ]
