# Generated by Django 5.2.6 on 2025-10-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_alter_classification_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='stage',
            field=models.CharField(choices=[('stage1', 'Estágio 1'), ('stage2', 'Estágio 2'), ('stage3', 'Estágio 3'), ('stage4', 'Estágio 4'), ('not_classifiable', 'Not Classifiable'), ('dtpi', 'DTPI')], default='not_classifiable', max_length=20),
        ),
    ]
