# Generated by Django 5.2.6 on 2025-09-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of the file for uniqueness', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='image',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename of the uploaded file', max_length=255, null=True),
        ),
    ]
