# Generated by Django 5.2.6 on 2025-10-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_file_hash_image_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the image', null=True),
        ),
    ]
